### PR TITLE
Update to API11

### PR DESCRIPTION
**Pull request by Zeffuro**

### CODE REVIEW

**Comment by TentouXIV** [comment]
bump

**Comment by rurri** [comment]
Nice work

**Comment by Cloud7050** [comment]
While we wait on a response, do you reckon there's a way to make this available via custom plugin repo?

**Comment by Zeffuro** [comment]
That would still require attick putting in a repo (and if he has time for that he would've already merged this). I'm not gonna make a repo for my fork since it's still atticks work. Best thing to do is wait or build the plugin yourself.

**Comment by Zeffuro** [comment]
I made a small change. I cleaned up the .idea folder that didn't need to be PRed and I fixed a crash that would happen if your configuration would still contain an action that has been deleted from the game since the new expansion (in my case that happened to be Dragoons Spineshatter Dive)

**Comment by Zeffuro** [comment]
Made more changes, it's now updated to API11

**Comment by Zeffuro** [comment]
I'm open to adopting the plugin btw in case you don't have time for this anymore.

**Comment by attickdoor** [comment]
let's ship it i suppose

**Pull request merged**
